# Generated by Django 4.2.7 on 2023-12-19 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='quantity',
            new_name='quantity1',
        ),
        migrations.AddField(
            model_name='stock',
            name='quantity2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stock',
            name='quantity3',
            field=models.IntegerField(default=0),
        ),
    ]
