# Generated by Django 4.2.7 on 2023-12-19 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_quantity_stock_quantity1_stock_quantity2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='arduinodata',
            name='humidity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='arduinodata',
            name='temperature',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
