# Generated by Django 4.2.7 on 2023-12-19 00:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_medicalkit_expiration_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalkit',
            name='expiration_date',
            field=models.DateField(default=datetime.datetime(2024, 12, 16, 0, 4, 58, 294239)),
        ),
    ]
