# Generated by Django 4.2.7 on 2023-12-19 00:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_medicalkit_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalkit',
            name='expiration_date',
            field=models.DateField(default=datetime.datetime(2024, 12, 16, 0, 58, 33, 80392)),
        ),
    ]
