# Generated by Django 4.2.7 on 2023-12-19 01:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_medicalkit_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalkit',
            name='expiration_date',
            field=models.DateField(default=datetime.datetime(2024, 12, 13, 1, 35, 27, 678351)),
        ),
    ]
