# Generated by Django 4.2.7 on 2023-12-19 02:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_medicalkit_expiration_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('link', models.URLField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='medicalkit',
            name='expiration_date',
            field=models.DateField(default=datetime.datetime(2024, 12, 13, 2, 28, 48, 800024)),
        ),
    ]
